[package]
name = "xor-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lsp-types = "0.94.0"
lsp-server = "0.7.0"
serde = "1.0.152"
serde_json = "1.0.93"
csv = "1.2"
